Chess game
floazema/Python-discord-bot pull request #4
Opened 2022-09-07 08:21 UTC by chaquentin

Vous pouvez critiquer tout sauf test.py qui est un test

2022-09-07 18:45 UTC, Saverio976 requested changes
en vrai gg, y a des coditions ça part dans le futur, jsp comment tu as fait pour pas t'embrouiller

2022-09-07 18:45 UTC, Saverio976 commented on chess_prog/Pieces/piece.py
> +    def same_pos(self, second_position) -> bool:
second_position type hint ?

2022-09-07 18:45 UTC, Saverio976 commented on chess_prog/Pieces/piece.py
> +    def is_empty(self, all_pieces: list):
en python on peut faire ça:
```py
list["Piece"]
```
et ça fera un type hint d'une liste avec dedans des objets de type Piece

2022-09-07 18:45 UTC, Saverio976 commented on chess_prog/Pieces/piece.py
> +    def move(self, x: int, y: int, all_piece: list):
list["Piece"]

2022-09-07 18:45 UTC, Saverio976 commented on chess_prog/Pieces/piece.py
> +        raise NotImplementedError("nit impl")
"not" pas "nit" ?

2022-09-07 18:45 UTC, Saverio976 commented on chess_prog/Pieces/piece.py
> +    def eat(self, x: int, y: int, all_piece: list):
list["Piece"]

2022-09-07 18:45 UTC, Saverio976 commented on chess_prog/Pieces/piece.py
> +                print("miam miam")
print dans une merge requests ?

2022-09-07 18:45 UTC, Saverio976 commented on chess_prog/Pieces/bishop.py
> +    def move(self, x: int, y: int, all_piece: list) -> bool:
en python on peut faire ça:

list["Piece"]

et ça fera un type hint d'une liste avec dedans des objets de type Piece

2022-09-07 18:45 UTC, Saverio976 commented on chess_prog/Pieces/king.py
> +    def move(self, x: int, y: int, all_piece: list):
peut-être verifier si il est en echec dans la prochaine position ?

où c'est prévu pour plus tard ?

2022-09-07 18:45 UTC, Saverio976 commented on chess_prog/Pieces/knight.py
> +    def move(self, x: int, y: int, all_piece: list):
en python on peut faire ça:

list["Piece"]

et ça fera un type hint d'une liste avec dedans des objets de type Piece

2022-09-07 18:45 UTC, Saverio976 commented on chess_prog/Pieces/king.py
> +    def move(self, x: int, y: int, all_piece: list):
en python on peut faire ça:

list["Piece"]

et ça fera un type hint d'une liste avec dedans des objets de type Piece

2022-09-07 18:45 UTC, Saverio976 commented on chess_prog/Pieces/pawn.py
> +    def move(self, x: int, y: int, all_piece: list) -> bool:
en python on peut faire ça:

list["Piece"]

et ça fera un type hint d'une liste avec dedans des objets de type Piece

2022-09-07 18:45 UTC, Saverio976 commented on chess_prog/Pieces/pawn.py
> +    def eat(self, x: int, y: int, all_piece: list):
list["Piece"]

2022-09-07 18:45 UTC, Saverio976 commented on chess_prog/Pieces/queen.py
> +    def move(self, x: int, y: int, all_piece: list):
list["Piece"]

2022-09-07 18:45 UTC, Saverio976 commented on chess_prog/Pieces/tower.py
> +    def move(self, x: int, y: int, all_pieces: list) -> bool:
list["Piece"]

2022-09-07 18:45 UTC, Saverio976 commented on chess_prog/Pieces/pawn.py
>          if self.white:
toute la partie du white vs black peut se faire avec un seul truc:

```py
            multip = -1 if self.white else 1
            if not Position(self.pos.x, self.pos.y + y).is_empty(all_piece):
                return False
            if y == 1 * multip:
                self.pos.y += 1 * multip
            elif y == 2 * multip:
                if not Position(self.pos.x, self.pos.y + (1 * multip)).is_empty(
                    all_piece
                ):
                    return False
                self.pos.y += 2 * multip
            else:
                return False
```

2022-09-07 19:01 UTC, chaquentin commented on chess_prog/Pieces/king.py
> +    def move(self, x: int, y: int, all_piece: list):
C'est pour plus tard

2022-09-07 19:01 UTC, chaquentin commented on chess_prog/Pieces/piece.py
> +        raise NotImplementedError("nit impl")
Oups

2022-09-07 19:41 UTC, chaquentin commented on chess_prog/Pieces/pawn.py
>          if self.white:
Merci, super idée. Je trouvais pas comment je pouvais l'implémenter sans faire 2 grands if

2022-09-08 06:29 UTC, Saverio976 requested changes

2022-09-08 06:29 UTC, Saverio976 commented on chess_prog/Pieces/pawn.py
> +        multip = -1 if self.white else 1
Tu as vérifié que ça marchait bien ?

2022-09-08 06:29 UTC, Saverio976 commented on chess_prog/Pieces/queen.py
> +    def __init__(self, isWhite, x, y):
Type hint pour les paramètres ?

2022-09-08 06:55 UTC, chaquentin commented on chess_prog/Pieces/pawn.py
> +        multip = -1 if self.white else 1
oui

2022-09-08 09:44 UTC, Saverio976 approved these changes
Good

2022-09-08 09:52 UTC, merged